name: Build Base AMI

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Setup Packer
        uses: hashicorp/setup-packer@main

      - name: Packer init
        run: packer init packer/base.pkr.hcl

      - name: Packer build
        run: packer build packer/base.pkr.hcl
